# Generated by Django 4.1.7 on 2023-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='chan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
